# syntax=docker/dockerfile:1.4

FROM node:23-alpine AS dev

WORKDIR /app

# Install pnpm via npm
RUN npm install -g pnpm

# Copy and install dependencies
COPY pnpm-lock.yaml ./
COPY package.json ./
RUN pnpm install

# Copy the rest of the files
COPY . .

EXPOSE 5173

ENV NODE_ENV=development

CMD ["pnpm", "dev", "--", "--host"]
