services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5555:5555"
    depends_on:
      - database
    volumes:
      - ./backend:/app

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
